import { useState, useEffect } from "react";
import Head from "next/head";

import style from "./Profile.module.scss";
export default function Profile() {
	const [first, setfirst] = useState(false);
	const [active, setactive] = useState(0);

	useEffect(() => {}, []);
	return (
		<div className={style.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
					integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
					crossorigin="anonymous"
					referrerpolicy="no-referrer"
				/>
			</Head>

			<div className={`${style.navbar} ${first ? style.mincontainer : ""}`}>
				<div className={style.search}>
					<i class="fa-solid fa-magnifying-glass"></i>
				</div>
				<div className={style.nav} style={{}}>
					<div onClick={() => setfirst(!first)} className={`flex ${style.color}`} style={{ flex: 1 }}>
						<i className={`fa-regular fa-square ${style.yellow}`}></i>
						<div style={{ width: "max-content" }}>Nat Geo</div>
					</div>
					<div
						onClick={() => setactive(0)}
						className={`flex ${!active == 0 ? style.colorGrey : style.color}`}>
						{first ? (
							<i
								className="fa-solid fa-house"
								style={{ width: "2.5rem", minWidth: "2.5rem", textAlign: "center" }}></i>
						) : (
							<div style={{ width: "max-content" }}>Nat Geo</div>
						)}
					</div>
					<div
						onClick={() => setactive(1)}
						className={`flex ${!active == 1 ? style.colorGrey : style.color}`}>
						{first ? (
							<i
								class="fa-solid fa-play"
								style={{ width: "2.5rem", minWidth: "2.5rem", textAlign: "center" }}></i>
						) : (
							<div style={{ width: "max-content" }}>Nat Geo</div>
						)}
					</div>
				</div>
			</div>
		</div>
	);
}
